// layer7-app/src/app/devs/devs.component.ts
import { Component, OnInit } from '@angular/core';
import { faGithub, faLinkedin, faTwitter } from '@fortawesome/free-brands-svg-icons';
import { faGlobeAmericas, faPenSquare } from '@fortawesome/free-solid-svg-icons';
import { Developer } from '../models';


@Component({
  selector: 'app-devs',
  templateUrl: './devs.component.html',
  styleUrls: ['./devs.component.scss']
})
export class DevsComponent implements OnInit {

  developers: Developer[] = [
    {
      name: 'Adam Swanson',
      img: '/assets/img/crisp.jpg',
      primaryLink: 'https://adam.layerseven.net',
      links: [
        { href: 'https://adam.layerseven.net', icon: faGlobeAmericas },
        { href: 'https://blog.layerseven.net', icon: faPenSquare },
        { href: 'https://github.com/theaswanson', icon: faGithub },
        { href: 'https://twitter.com/crisp2020', icon: faTwitter },
        { href: 'https://linkedin.com/in/adam-swanson/', icon: faLinkedin },
      ]
    }
  ];

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="developers">
  <div class="title">
    <h1>Developers</h1>
  </div>
  <div class="developer" *ngFor="let developer of developers">
    <div class="image">
      <a [href]="developer.primaryLink" target="_blank">
        <img [src]="[developer.img]" />
      </a>
    </div>
    <div class="name">{{developer.name}}</div>
    <div class="icon-row">
      <a [href]="[link.href]" target="_blank" *ngFor="let link of developer.links">
        <fa-icon [icon]="link.icon" size="lg"></fa-icon>
      </a>
    </div>
  </div>
</div>

// src/pages/Home/Devs.tsx
import { Create, GitHub, LinkedIn, Public, Twitter } from "@mui/icons-material";
import { Developer } from "../../types";
import AdamImg from '../../assets/crisp.jpg';
import './Devs.scss'

export const Devs = () => {
  const developers: Developer[] = [
    {
      name: 'Adam Swanson',
      img: AdamImg,
      primaryLink: 'https://adam.layerseven.net',
      links: [
        { url: 'https://adam.layerseven.net', icon: <Public /> },
        { url: 'https://blog.layerseven.net', icon: <Create /> },
        { url: 'https://github.com/theaswanson', icon: <GitHub /> },
        { url: 'https://twitter.com/crisp2020', icon: <Twitter /> },
        { url: 'https://linkedin.com/in/adam-swanson/', icon: <LinkedIn /> },
      ]
    }
  ];

  return (
    <div className="developers">
      <div className="title">
        <h3>Developers</h3>
      </div>
      {developers.map(developer => (
        <div className="developer">
          <div className="image">
            <a href={developer.primaryLink} target="_blank">
              <img src={developer.img} />
            </a>
          </div>
          <div className="name">{developer.name}</div>
          <div className="icon-row">
            {developer.links.map(link => (
              <a href={link.url} target="_blank">
                {link.icon}
              </a>
            ))}
          </div>
        </div >
      ))}
    </div >
  )
}
