// layer7-app/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { faDiscord, faTwitter } from '@fortawesome/free-brands-svg-icons';
import { faEnvelope } from '@fortawesome/free-regular-svg-icons';
import { SocialItem } from '../models';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  links: SocialItem[] = [
    { href: 'https://twitter.com/Layer7Official', icon: faTwitter },
    { href: 'https://discord.gg/ZFbYZNtDsa', icon: faDiscord },
    { href: 'mailto:layersevenmail@gmail.com', icon: faEnvelope },
  ]

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container-fluid">
  <div class="home">
    <div class="logo">
      <img src="../../assets/img/logo.png" />
    </div>
    <div class="title">
      <h1>Layer 7</h1>
    </div>
    <div class="description">
      <span>Software development. Server hosting. The cool stuff.</span>
    </div>
    <div class="icon-row">
      <a [href]="[link.href]" target="_blank" *ngFor="let link of links">
        <fa-icon [icon]="link.icon" size="lg"></fa-icon>
      </a>
    </div>
  </div>
  <app-devs></app-devs>
</div>

// src/pages/Home/index.tsx
import { Email, Twitter } from "@mui/icons-material";
import { SocialItem } from "../../types";
import { Devs } from "./Devs";
import Logo from '../../assets/logo.png';
import './index.scss'
import Discord from "../../components/icons/Discord";

export const Home = () => {
  const socials: SocialItem[] = [
    { url: 'https://twitter.com/Layer7Official', icon: <Twitter /> },
    { url: 'https://discord.gg/ZFbYZNtDsa', icon: <Discord /> },
    { url: 'mailto:layersevenmail@gmail.com', icon: <Email /> },
  ];

  return (
    <div className="container-fluid">
      <div className="home">
        <div className="logo">
          <img src={Logo} />
        </div>
        <div className="title">
          <h1>Layer 7</h1>
        </div>
        <div className="description">
          <span>Software development. Server hosting. The cool stuff.</span>
        </div>
        <div className="icon-row">
          {socials.map((social) => (
            <a href={social.url} target="_blank">
              {social.icon}
            </a>
          ))}
        </div>
      </div>
      <Devs />
    </div>
  )
}
